### ISSUE TITLE
Newly introduced methods 'indexBy' and 'sample'

### ISSUE THREAD

**Issue by nvdnkpr** [floydwch/angular-underscore#17]
Hello floydsoft,

thank you for your work, especially the filter stuff works like a charm ;)
What I noticed is that your list of filters must be based on an earlier version (earlier than 1.5.2) of underscore because there are two new methods, introduced in version 1.5.2

Some of the newly introduced methods might possibly make no sense from an template view, but they still can be used as (per definition) filters in controllers using $filter (marked with an :small_red_triangle: )

**Collections**
- [indexBy](http://underscorejs.org/#indexBy)
- [sample](http://underscorejs.org/#sample)

**Array**
- [partition](http://underscorejs.org/#partition) :small_red_triangle:

**Utility**
- [unescape](http://underscorejs.org/#unescape)

**Comment by floydwch** [comment]
Sorry for the late reply, and I've confirmed these new methods, thank you!
