### ISSUE TITLE
Gem?

### ISSUE THREAD

**Issue by shacker** [floydwch/angular-underscore#2]
Awesome. Has anyone packaged this module up as a ruby gem?

**Comment by floydwch** [comment]
No, maybe you could make the gem?

**Comment by shacker** [comment]
I'm willing in spirit, but I haven't got the chops for that yet just yet, sorry.

**Comment by floydwch** [comment]
So why you want to package it gem?

Just loading JS from gem?

**Comment by shacker** [comment]
Because then it becomes part of the Rails asset pipeline, with integrated minification, etc.

**Comment by floydwch** [comment]
Not a rails user, I suggest you can reference the setting of https://github.com/rweng/underscore-rails and add dependencies of https://github.com/ludicast/angular-rails and https://github.com/rweng/underscore-rails, good luck.
